[phases.setup]
providers = ["...", "python"]
commands = [
  "PIPENV_VENV_IN_PROJECT=1 pipenv install --deploy"
]

[phases.build]
commands = [
  "pipenv run python -m pip install fastapi uvicorn asyncpg sqlalchemy databases alembic psycopg2-binary greenlet celery redis aiosmtpd",
  "pipenv run alembic upgrade head"
]